# for functions in bidcell/processing

cpu_params:
  n_processes: 16 # number of CPUs for multiprocessing

paths_params:
  dataset: dataset_xenium_breast1 # name of dataset under data/
  fp_dapi: morphology_mip.ome.tif # name of DAPI image
  fp_transcripts: transcripts.csv.gz # name of transcripts file
  fp_ref: ../../data/sc_references/sc_breast.csv 

transcript_params:
  x_col: x_location # name of x location column in transcripts file
  y_col: y_location # name of y location column in transcripts file
  gene_col: feature_name # name of genes column in transcripts file

affine_params:
  target_pix_um: 1.0 # microns per pixel to perform segmentation 
  base_pix_x: 0.2125 # convert to microns along width by multiplying the original pixels by base_pix_x microns per pixel
  base_pix_y: 0.2125 # convert to microns along width by multiplying the original pixels by base_pix_y microns per pixel
  base_ts_x: 1.0 # convert between transcript locations and target pixels along width
  base_ts_y: 1.0 # convert between transcript locations and target pixels along height
  global_shift_x: 0 # additional adjustment to align transcripts to DAPI in target pixels along image width
  global_shift_y: 0 # additional adjustment to align transcripts to DAPI in target pixels along image height


# for functions in bidcell/model

model_params:
  name: custom # 
  patch_size: 48 # size of transcriptomic image patches for input to DL model
  elongated: # list of elongated cell types that are in the single-cell reference
  - Endothelial
  - Fibroblasts
  - Myofibroblasts
  - SMC

training_params:
  total_epochs: 1 # number of training epochs
  learning_rate: 1.0e-05 # 
  beta1: 0.9 # 
  beta2: 0.999 # 
  weight_decay: 0.0001 # 
  optimizer: adam
  ne_weight: 1
  os_weight: 1
  cc_weight: 1
  ov_weight: 1
  pos_weight: 1
  neg_weight: 1
  epoch: 1 # epoch to test 
  steps: 4000 # number of training steps

save_freqs:
  model_freq: 1000 # number of training steps per model save
  sample_freq: 100 # number of training steps per sample save 

data_sources:
  expr_fp: "../../data/dataset_xenium_breast1/expr_maps/expr_maps_input_patches_"
  expr_fp_ext: ".hdf5"
  nuclei_fp: "../../data/dataset_xenium_breast1/nuclei.tif"
  nuclei_types_fp: "../../data/dataset_xenium_breast1/nuclei_cell_type.h5"
  pos_markers_fp: "../../data/sc_references/sc_breast_markers_pos.csv"
  neg_markers_fp: "../../data/sc_references/sc_breast_markers_neg.csv"
  atlas_fp: "../../data/sc_references/sc_breast.csv"
  gene_names: "../../data/dataset_xenium_breast1/all_gene_names.txt"

experiment_dirs: # directory names for each experiment under bidcell/model/experiments
  load_dir: last
  model_dir: models
  test_output_dir: test_output
  samples_dir: samples









# data_params:
#   patch_size: 48
#   elongated:
#   - Endothelial
#   - Fibroblasts
#   - Myofibroblasts
#   - SMC




data_params:
  patch_size: 64
  elongated: ["Endothelial", "Fibroblasts", "Myofibroblasts", "SMC"]
  interpolator: 'sitkBSpline' # This is an enumerated value, here None is not allowed
  resampledPixelSpacing: # This disables resampling, as it is interpreted as None, to enable it, specify spacing in x, y, z as [x, y , z]
  weightingNorm: # If no value is specified, it is interpreted as None

imageType:
  Original: {} # for dictionaries / mappings, None values are not allowed, '{}' is interpreted as an empty dictionary
  LoG:
    sigma: [1.0, 2.0, 3.0, 4.0, 5.0]  # If you include sigma values >5, remember to also increase the padDistance.
  Wavelet: {}

# Featureclasses, from which features must be calculated. If a featureclass is not mentioned, no features are calculated
# for that class. Otherwise, the specified features are calculated, or, if none are specified, all are calculated (excluding redundant/deprecated features).
featureClass:
  # redundant Compactness 1, Compactness 2 an Spherical Disproportion features are disabled by default, they can be
  # enabled by specifying individual feature names (as is done for glcm) and including them in the list.
  shape:
  firstorder: [] # specifying an empty list has the same effect as specifying nothing.
  glcm:  # Disable SumAverage by specifying all other GLCM features available
    - 'Autocorrelation'
    - 'JointAverage'
    - 'ClusterProminence'
    - 'ClusterShade'
    - 'ClusterTendency'
    - 'Contrast'
    - 'Correlation'
    - 'DifferenceAverage'
    - 'DifferenceEntropy'
    - 'DifferenceVariance'
    - 'JointEnergy'
    - 'JointEntropy'
    - 'Imc1'
    - 'Imc2'
    - 'Idm'
    - 'Idmn'
    - 'Id'
    - 'Idn'
    - 'InverseVariance'
    - 'MaximumProbability'
    - 'SumEntropy'
    - 'SumSquares'
  glrlm: # for lists none values are allowed, in this case, all features are enabled
  glszm:
  ngtdm:
  gldm:  # contains deprecated features, but as no individual features are specified, the deprecated features are not enabled
